/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package naturallangfrontenddb;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;

/**
 *
 * @author connorbray
 */
public class connectUI extends javax.swing.JFrame {

    /**
     * Creates new form connectUI
     */
    public connectUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("URL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 70, 24, 16);

        jLabel2.setText("Database Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 98, 16);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 62, 16);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 59, 16);
        getContentPane().add(txtName);
        txtName.setBounds(159, 98, 180, 28);
        getContentPane().add(txtUser);
        txtUser.setBounds(160, 130, 180, 28);
        getContentPane().add(txtPass);
        txtPass.setBounds(160, 160, 180, 28);

        txtURL.setText("jdbc:mysql://test.com/");
        getContentPane().add(txtURL);
        txtURL.setBounds(160, 70, 180, 28);

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        getContentPane().add(btnConnect);
        btnConnect.setBounds(210, 220, 96, 29);

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoad);
        btnLoad.setBounds(80, 220, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        boolean connected = databaseConn.connect(txtURL.getText(), txtName.getText(), txtUser.getText(), txtPass.getText());
        if (connected)
        {
          managerUI mui = new managerUI();
          mui.setLocationRelativeTo(null);
          mui.setSize(400,300);
          this.setVisible(false);
          mui.setVisible(true);
        }

    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try
        {    
          JFileChooser chooser = new JFileChooser();
          chooser.showOpenDialog(null);
          File openFile = chooser.getSelectedFile();
          BufferedReader readFile = new BufferedReader(new FileReader(openFile));
          String url = readFile.readLine();
          String name = readFile.readLine();
          String username = readFile.readLine();
          String pass = readFile.readLine();
          
          txtURL.setText(url);
          txtName.setText(name);
          txtUser.setText(username);
          txtPass.setText(pass);
          
         
        }
        catch(Exception e)
        {
           System.err.println(e);   
        
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new connectUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
