/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package naturallangfrontenddb;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JFileChooser;

/**
 *
 * @author connorbray
 */
public class managerUI extends javax.swing.JFrame {

    /**
     * Creates new form managerUI
     */
    public managerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        tabPane = new javax.swing.JTabbedPane();
        qryPnl = new javax.swing.JPanel();
        txtQuery = new javax.swing.JTextField();
        btnQuery = new javax.swing.JButton();
        optionsPnl = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        saveTab = new javax.swing.JButton();
        btnTestPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        qryPnl.setLayout(null);

        txtQuery.setText("Enter query Here");
        qryPnl.add(txtQuery);
        txtQuery.setBounds(10, 20, 347, 27);

        btnQuery.setText("Query");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });
        qryPnl.add(btnQuery);
        btnQuery.setBounds(10, 60, 128, 29);

        tabPane.addTab("Query", qryPnl);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        saveTab.setText("Save DB Login Info");
        saveTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTabActionPerformed(evt);
            }
        });

        btnTestPrint.setText("Test Print");
        btnTestPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestPrintActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout optionsPnlLayout = new org.jdesktop.layout.GroupLayout(optionsPnl);
        optionsPnl.setLayout(optionsPnlLayout);
        optionsPnlLayout.setHorizontalGroup(
            optionsPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionsPnlLayout.createSequentialGroup()
                .add(114, 114, 114)
                .add(optionsPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(saveTab, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnTestPrint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnExit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        optionsPnlLayout.setVerticalGroup(
            optionsPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionsPnlLayout.createSequentialGroup()
                .add(32, 32, 32)
                .add(saveTab)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnTestPrint)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnExit)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        tabPane.addTab("Options", optionsPnl);

        getContentPane().add(tabPane);
        tabPane.setBounds(0, 0, 380, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        databaseConn.closeConn();
        System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnTestPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestPrintActionPerformed
        databaseConn.testPrint();
}//GEN-LAST:event_btnTestPrintActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        String query = txtQuery.getText();
        databaseConn.genericQueryDB(query);
}//GEN-LAST:event_btnQueryActionPerformed

    private void saveTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTabActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showSaveDialog(null);
            FileWriter saveFile = new FileWriter(chooser.getSelectedFile() + ".txt");
            BufferedWriter out = new BufferedWriter(saveFile);
            out.write(databaseConn.url + "\n");
            out.write(databaseConn.dbName + "\n");
            out.write(databaseConn.userName + "\n");
            out.write(databaseConn.password + "\n");
            out.close();
        } catch(Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_saveTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new managerUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnTestPrint;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel optionsPnl;
    private javax.swing.JPanel qryPnl;
    private javax.swing.JButton saveTab;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTextField txtQuery;
    // End of variables declaration//GEN-END:variables
}
